name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # <--- wymagane do zapisu cache do ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          tags: localbuild:latest
          load: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-cache:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-cache:cache,mode=max

    - name: Scan image for CVEs (Trivy)
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: localbuild:${{ env.TAG }}
        severity: CRITICAL,HIGH
        exit-code: 1

    - name: Build and push multi-arch image
      if: success()
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}:cache
        cache-to: type=registry,ref=${{ env.CACHE_IMAGE }}:cache,mode=max
